DROP TABLE IF EXISTS diccionario;

CREATE TABLE diccionario (
	Id INT(11) NOT NULL AUTO_INCREMENT,
	Hitza VARCHAR(30) NOT NULL,
	Palabra VARCHAR(30) NOT NULL,
	Word VARCHAR(30) NOT NULL,
	Parole VARCHAR(30) NOT NULL,
	PRIMARY KEY (Id) 
);
